import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ScrollToTop from "@/components/ui/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollToTop />
        <nav className="bg-white text-black px-5 py-5 lg:py-7 fixed w-full shadow">
          <ul className="flex justify-center gap-9">
            <li>
              <Link
                href="/"
                className="border border-cyan-600 text-cyan-600 py-2 px-7 rounded hover:bg-cyan-600 hover:text-white"
              >
                Home
              </Link>
            </li>
            <li>
              <Link
                href="/products"
                className="border border-cyan-600 text-cyan-600 py-2 px-7 rounded hover:bg-cyan-600 hover:text-white"
              >
                Product
              </Link>
            </li>
          </ul>
        </nav>
        <div className="bg-white text-black pt-20">{children}</div>
      </body>
    </html>
  );
}
